#!/usr/bin/env bash

#===============================
# Start of the Display Settings
#===============================

DETECT_PRIMARY=0
OUTPUTS=()
ADVANCED_MODE=0

#=============================
# End of the Display Settings
#=============================

case "$1" in
  '-h'|'--help') cat << EOF
usage: srd [-h] [-b <int>] [-g <int>] [-f]

A simpler interface for common xrandr options

options:
  -h, --help  show this help message and exit
  -b <int>    Set the brightness value (default: 1)
  -g <int>    Set the same gamma value for all channels, or adjust each one individually (default: 1)
  -f          Invert the advanced mode value for this run only

Restore xrandr default settings when invoked without any flags

EOF
  exit 0
  ;;
esac

[[ "$@" == *'-f'* ]] && { ADVANCED_MODE=$(( 1 - ADVANCED_MODE )); shift 1; }

if (( ${#OUTPUTS[@]} == 0 )); then
  if (( DETECT_PRIMARY == 0 )); then
    while read -r line; do
      if [[ "$line" == *' connected'* ]]; then
        OUTPUTS+=("${line%% *}")
      fi
    done < <(/usr/bin/xrandr)
  else
    while read -r line; do
      if [[ "$line" == *'primary'* ]]; then
        OUTPUTS+=("${line%% *}")
      fi
    done < <(/usr/bin/xrandr)
  fi
fi

b=1; g=1
for arg; do
  case "$1" in
    '-b')
      (( ADVANCED_MODE == 0 )) && {
        if ((
          $2 > 2 &&
          $2 < 9
        )); then
          b="0.$2"
          shift 2
        else
          echo "The brightness value is out of range: $2"
          exit 1
        fi 2>/dev/null
      } || {
        if [[ "$2" =~ 0\.[1-9]|1\.[0-9]|2 ]]; then
          b="$2"
          shift 2
        else
          echo "The brightness value is out of range: $2"
          exit 1
        fi
      }
      ;;
    '-g')
      (( ADVANCED_MODE == 0 )) && {
        if ((
          $2 > 2 &&
          $2 < 9
        )); then
          g="0.$2"
          shift 2
        else
          echo "The gamma value is out of range: $2"
          exit 1
        fi 2>/dev/null
      } || {
        if [[ "$2" =~ ^(0\.0?[1-9][0-9]?|1(\.[0-9][0-9]?)?|2),(0\.0?[1-9][0-9]?|1(\.[0-9][0-9]?)?|2),(0\.0?[1-9][0-9]?|1(\.[0-9][0-9]?)?|2)$|^[1-9]$ ]]; then
          g="${2//,/:}"
          shift 2
        else
          echo "The gamma value is out of range: $2"
          exit 1
        fi
      }
      ;;
  esac
done

full_command=()

for output in "${OUTPUTS[@]}"; do
  full_command+=(
    --output "$output"
    --brightness "$b"
    --gamma "$g"
  )
done

xrandr "${full_command[@]}"
